---
title: "argon-visualization"
author: "Robert Jankowski"
date: "16/10/2019"
output: html_document
---

```{r setup, include=FALSE}
# E_mean od tau
# H od t
# E_k, V, P od t

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
library(scales)
library(latex2exp)
```

### Testing stability
```{r}
stability <- read.csv("output/stability.csv", header = F)
colnames(stability) <- c("tau", "H", "P", "T")
head(stability)
```

```{r, fig.width=15, fig.height=4}
h <- ggplot(stability) + 
    geom_point(aes(tau, H)) + 
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x))) +
    # labs(title = "Hamiltonian") + 
    labs(y = "H [kJ/mol]",  x = TeX("$\\tau$")) +
    theme_light() + 
    theme(text = element_text(size = 14))

p <- ggplot(stability) + 
    geom_point(aes(tau, P)) + 
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x))) +
    # labs(title = "Pressure") + 
    labs(y = "P [x 16.6 atm.]", x = TeX("$\\tau$")) +
    theme_light() + 
    theme(text = element_text(size = 14))

t <- ggplot(stability) + 
    geom_point(aes(tau, T)) + 
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x))) +
    # labs(title = "Temperature") + 
    labs(y = "T [K]",  x = TeX("$\\tau$")) +
    theme_light() + 
    theme(text = element_text(size = 14))

# ggsave(filename = "stability.png", grid.arrange(h, p, t, nrow = 1), width = 12, height = 4)
#grid.arrange(h, p, t, nrow = 1)
# ggsave(filename="plots/5_1_stability_H.pdf", plot=h, width = 6, height = 3, units = "in")
# ggsave(filename="plots/5_1_stability_P.pdf", plot=p, width = 6, height = 3, units = "in")
# ggsave(filename="plots/5_1_stability_T.pdf", plot=t, width = 6, height = 3, units = "in")
```



```{r}
# library(latex2exp)
tau_e6 <- read.csv("output/5_1_out_tau=1e-6.csv", header = F)
tau_e2 <- read.csv("output/5_1_out_tau=1e-2.csv", header = F)
tau_e3 <- read.csv("output/5_1_out_tau=1e-3.csv", header = F)


colnames(tau_e6) <- c("t", "H", "V", "T", "P")
colnames(tau_e2) <- c("t", "H", "V", "T", "P")
colnames(tau_e3) <- c("t", "H", "V", "T", "P")
```

### Hamiltonian
```{r, fig.width=10, fig.height=5}
h_compare <- ggplot(tau_e2, aes(t, H)) +
    geom_point(aes(color = "tau = 10^-2")) +
    geom_point(data = tau_e3, aes(color = "tau = 10^-3")) +
    geom_point(data = tau_e6, aes(color = "tau = 10^-6"), alpha = 0.08) +
    labs(x = "t [ps]", y = "H [kJ/mol]") +
    theme_light() + 
    scale_color_discrete(labels = unname(TeX(c("$\\tau = 10^{-2}", "$\\tau = 10^{-3}", "$\\tau = 10^{-6}")))) + 
    theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14))

# ggsave(filename = "h_compare.png", h_compare, width = 12, height = 6)
h_compare 

ggsave(filename="plots/5_1_tau_compare_H.pdf", plot=h_compare, width = 6, height = 4, units = "in")
```

### Temperature
```{r, fig.width=10, fig.height=5}
t_compare <- ggplot(tau_e2, aes(t, T)) +
    geom_point(aes(color = "tau = 10^-2")) +
    geom_point(data = tau_e6, aes(color = "tau = 10^-6"), alpha = 0.6) +
    geom_point(data = tau_e3, aes(color = "tau = 10^-3")) +
    labs(x = "t [ps]", y = "T [K]") +
    theme_light() + 
    scale_color_discrete(labels = unname(TeX(c("$\\tau = 10^{-2}", "$\\tau = 10^{-3}", "$\\tau = 10^{-6}")))) + 
    theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14))

# ggsave(filename = "t_compare.png", t_compare, width = 12, height = 6)
t_compare

# ggsave(filename="plots/5_1_tau_compare_T.pdf", plot=t_compare,  width = 6, height = 4, units = "in")
```

### Pressure
```{r, fig.width=10, fig.height=5}
p_compare <- ggplot(tau_e2, aes(t, P)) +
    geom_point(aes(color = "tau = 10^-2")) +
    geom_point(data = tau_e6, aes(color = "tau = 10^-6")) +
    geom_point(data = tau_e3, aes(color = "tau = 10^-3")) +
    labs(x = "t [ps]", y = "P [x 16.6 atm.]") + # title = "Pressure"
    theme_light() + 
    scale_color_discrete(labels = unname(TeX(c("$\\tau = 10^{-2}", "$\\tau = 10^{-3}", "$\\tau = 10^{-6}")))) + 
    theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14))


# ggsave(filename = "p_compare.png", p_compare, width = 12, height = 6)
p_compare
# ggsave(filename="plots/5_1_tau_compare_P.pdf", plot=p_compare, width = 6, height = 4, units = "in")
```


## 5.2 Kryształ
```{r}
a_testing <- read.csv("output/a_testing.csv", header = F)
colnames(a_testing) <- c("a", "V")
```

```{r}
a_min <- a_testing %>%
    filter(V == min(a_testing$V))
a_min
```


```{r}
a_plot <- ggplot(a_testing) +
    geom_point(aes(a, V)) +
    geom_vline(xintercept = a_min$a, color = "red") + 
    labs(x = "a [nm]", y = "V [kJ/mol]") + 
    theme_light() +
    theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14))

# ggsave(filename="plots/5_2_a_testing.pdf", plot=a_plot, width = 6, height = 4, units = "in")
a_plot
```


```{r}
testing_T_mean <- read.csv("output/5_2_out_tau=1e-4.csv", header = F)
colnames(testing_T_mean) <- c("t", "H", "V", "T", "P")
```

```{r}
testing_T_mean_plot <- ggplot(testing_T_mean) +
    geom_point(aes(t, T), alpha = 0.3) + 
    labs(x = "t [ps]", y = "T [K]") +
    theme_light() +
        theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14))

# ggsave(filename="plots/5_2_T_mean.pdf", plot=testing_T_mean_plot, width = 6, height = 4, units = "in")
```

## 5.3 Topnienie kryształu 

```{r}
T070 <- read.csv("output/5_3_out_T0=70.0.csv", header = F)
T080 <- read.csv("output/5_3_out_T0=80.0.csv", header = F)
T090 <- read.csv("output/5_3_out_T0=90.0.csv", header = F)
T0100 <- read.csv("output/5_3_out_T0=100.0.csv", header = F)

colnames(T070) <- c("t", "H", "V", "T", "P")
colnames(T080) <- c("t", "H", "V", "T", "P")
colnames(T090) <- c("t", "H", "V", "T", "P")
colnames(T0100) <- c("t", "H", "V", "T", "P")
```

```{r, fig.width=10, fig.height=7}
melt_plot <- ggplot() +
    geom_point(data = T070, aes(t, T, color = "70K"), size= 0.5) +
    geom_point(data = T080, aes(t, T, color = "80K"), size= 0.5) +
    geom_point(data = T090, aes(t, T, color = "90K"), size= 0.5) +
    geom_point(data = T0100, aes(t, T, color = "100K"), size= 0.5) +
    labs(x = "t [ps]", y = "T [K]", color = "T0") +
    theme_light() +
    theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14)) +
    guides(color = guide_legend(override.aes = list(size=3)))

# ggsave(filename="plots/5_3_T0_melt.pdf", plot=melt_plot, width = 6, height = 4, units = "in")
melt_plot
```

## 5.4 Gaz

### Finding right `S0`

```{r}
s0_testing <- read.csv("output/5_4_S0_testing_tau=1.0E-4.csv", header = F)
colnames(s0_testing) <- c("S0", "T", "P")
```

```{r}
s0_min <- s0_testing[39,]
```

```{r}
s0_plot <- ggplot(s0_testing) + 
    geom_point(aes(S0, T)) +
    geom_vline(xintercept = s0_min$S0, color = "red") +
    theme_light() +
    ylab("T [K]") +
        theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14)) +
    guides(color = guide_legend(override.aes = list(size=3)))

# ggsave(filename="plots/5_4_S0.pdf", plot=s0_plot, width = 6, height = 4, units = "in")
s0_plot
```


```{r}
ggplot(s0_testing) + 
    geom_point(aes(S0, P)) +
    geom_vline(xintercept = s0_min$S0, color = "blue") +
    theme_light()
```



```{r}
S0200 <- read.csv("output/5_4_out_S0=0.0.csv", header = F)
S010000 <- read.csv("output/5_4_out_S0=10000.0.csv", header = F)
S020000 <- read.csv("output/5_4_out_S0=19000.0.csv", header = F)

colnames(S0200) <- c("t", "H", "V", "T", "P")
colnames(S010000) <- c("t", "H", "V", "T", "P")
colnames(S020000) <- c("t", "H", "V", "T", "P")
```

```{r, fig.width=12, fig.height=5}
ggplot() + 
    geom_point(data = S0200, aes(t, P, color = "So=0"), alpha = 1) +
    geom_point(data = S010000, aes(t, P, color = "So=10000"), alpha = 0.1) +
    geom_point(data = S020000, aes(t, P, color = "So=19000"), alpha = 0.05) +
    labs(x = "t [ps]", y = "P [x 16.6 atm.]") +
    theme_light() +
        theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14)) +
    guides(color = guide_legend(override.aes = list(size=3)))
```


```{r, fig.width=12, fig.height=5}
ggplot() + 
    geom_point(data = S0200, aes(t, T, color = "So=0"), alpha = 1) +
    geom_point(data = S010000, aes(t, T, color = "So=10000"), alpha = 0.1) +
    geom_point(data = S020000, aes(t, T, color = "So=19000"), alpha = 0.03) +
   theme_light() +
        theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14)) +
    guides(color = guide_legend(override.aes = list(size=3)))
```

P(T)

```{r}
ideal_gas_testing <- read.csv("output/5_4_Ideal_gas_testing.csv", header = F)

colnames(ideal_gas_testing) <- c("T0", "T", "P")
```

```{r}
ideal_gas_testing$T
```

```{r}
L <- 2.3
N <- 125
k_b <- 0.00831

T <- seq(100, 1600, 50)
P <- 3 / 2 * N * k_b * T / (4 / 3 * pi * L^3)

ideal <- data.frame(T = T, P = P)
```


```{r, warning=FALSE, message=FALSE}
p_t <- ggplot(ideal_gas_testing) +
    geom_point(aes(T, P, color = "Symulacja")) +
    geom_line(data = ideal, aes(T, P, color = "Gaz doskonały")) +
    labs(x = "T [K]", y = "P [x 16.6 atm.]") +
   theme_light() +
        theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14)) +
    guides(color = guide_legend(override.aes = list(size=3)))

# ggsave(filename="plots/5_4_p_t.pdf", plot=p_t, width = 6, height = 4, units = "in")
p_t
```


```{r}
T0500 <- read.csv("output/5_4_out_T0=500.0.csv", header = F)
T01000 <- read.csv("output/5_4_out_T0=1000.0.csv", header = F)
T01500 <- read.csv("output/5_4_out_T0=1500.0.csv", header = F)
T02000 <- read.csv("output/5_4_out_T0=2000.0.csv", header = F)

colnames(T0500) <- c("t", "H", "V", "T", "P")
colnames(T01000) <- c("t", "H", "V", "T", "P")
colnames(T01500) <- c("t", "H", "V", "T", "P")
colnames(T02000) <- c("t", "H", "V", "T", "P")
```

```{r, fig.width=12, fig.height=5}
t0_compare <- ggplot() + 
    geom_line(data = T0500, aes(t, T, color = "500 K"), alpha = 1) +
    geom_line(data = T01000, aes(t, T, color = "1000 K"), alpha = 1) +
    geom_line(data = T01500, aes(t, T, color = "1500 K"), alpha = 1) +
    geom_line(data = T02000, aes(t, T, color = "2000 K"), alpha = 1) +
    geom_vline(xintercept = 1.9, alpha = 0.4) +
    labs(x = "t [ps]", y = "T [K]", color = "T0") +
   theme_light() +
        theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14)) +
    guides(color = guide_legend(override.aes = list(size=3)))

# ggsave(filename="plots/5_4_t0_compare.pdf", plot=t0_compare, width = 6, height = 4, units = "in")
t0_compare  
```

```{r, fig.width=12, fig.height=5}
p_compare <- ggplot() + 
    geom_line(data = T0500, aes(t, P, color = "500 K"), alpha = 1) +
    geom_line(data = T01000, aes(t, P, color = "1000 K"), alpha = 1) +
    geom_line(data = T01500, aes(t, P, color = "1500 K"), alpha = 1) +
    geom_line(data = T02000, aes(t, P, color = "2000 K"), alpha = 1) +
    geom_vline(xintercept = 1.9, alpha = 0.4) +
    labs(x = "t [ps]", y = "P [x 16.6 atm.]") +
       theme_light() +
        theme(legend.position = "top", legend.title = element_blank(),
          legend.text = element_text(size = 13), text = element_text(size = 14)) +
    guides(color = guide_legend(override.aes = list(size=3)))

# ggsave(filename="plots/5_4_p_compare.pdf", plot=p_compare, width = 6, height = 4, units = "in")
p_compare
```
